language: java

dist: trusty
sudo: required

services:
  - docker

script:
  - docker-compose config
  - docker-compose pull jenkins registry

notifications:
  email:
    on_success: never
    on_failure: change
