version: '2'

networks:
  fmms:
    driver: bridge

services:

  database:
    restart: always
    build: database
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - variables.env
    networks:
      - fmms

  backend:
    restart: always
    build: backend
    depends_on:
      - database
    ports:
      - "8080:80"
    expose:
      - 80
    env_file:
      - variables.env
    networks:
      - fmms

  frontend:
    restart: always
    build: frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    expose:
      - 4200
    env_file:
      - variables.env
    networks:
      - fmms

volumes:
  postgres:
    driver: local
