version: '2'

networks:
  fmms:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.0.0/24

services:
  backend:
    restart: always
    image: 172.16.0.11:5000/backend
#    ports:
#      - 28080:8080
    expose:
      - 8080
    env_file:
      - variables.env
    volumes:
      - maven:/root/.m2
    networks:
      fmms:
        ipv4_address: 172.16.0.3

  frontend:
    restart: always
    image: 172.16.0.11:5000/frontend
    command: ["--env=staging", "--no-live-reload", "--aot", "--build-optimizer", "--no-watch", "--public-host", "modulemanagement.fontysvenlo.org", "--proxy-config", "proxy.json"]
    depends_on:
      - backend
#    ports:
#      - 24200:4200
    expose:
      - 4200
    networks:
      fmms:
        ipv4_address: 172.16.0.2

  registry:
    restart: always
    image: registry:2
    expose:
      - 5000
    networks:
      fmms:
        ipv4_address: 172.16.0.10

  jenkins:
    restart: unless-stopped
    build: jenkins
    ports:
      - 28080:8080
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      fmms:
        ipv4_address: 172.16.0.11

volumes:
  maven:
    driver: local
  jenkins:
    driver: local
