version: '2'

networks:
  fmms:
    driver: bridge
    ipam:
      driver: default
      config:
        subnet: 172.16.0.0/24

services:
  backend:
    restart: always
    build: backend
    ports:
      - 28080:8080
    expose:
      - 8080
    env_file:
      - variables.env
    volumes:
      - maven:/root/.m2
    networks:
      fmms:
          ipv4_address: 172.16.0.3

  frontend:
    restart: always
    build: frontend
    command: ["--env=staging", " --live-reload=false"]
    depends_on:
      - backend
    ports:
      - 24200:4200
    expose:
      - 4200
      networks:
        fmms:
            ipv4_address: 172.16.0.2
    environment:
      - APPLICATION_ENV=staging

volumes:
  maven:
    driver: local
