version: '2'

networks:
  nulap:
    driver: bridge

services:

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    ports:
       - "28392:80"
    env_file:
      - variables.env
    networks:
      - nulap

  redis:
    restart: always
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - redis:/data
    networks:
      - nulap

#  elasticsearch:
#    image: elasticsearch:alpine
#    restart: always
#    expose:
#      - "9200"
#      - "9300"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    env_file:
#      - variables.env
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    networks:
#      - nulap

  nulap:
    image: lukeelten/nulap:latest
    restart: always
    expose:
      - 80
      - 443
    ports:
      - "28390:80"
    depends_on:
      - redis
#      - elasticsearch
    env_file:
      - variables.env
    networks:
      - nulap

volumes:
  redis:
    driver: local
  esdata:
    driver: local
