version: '2'

networks:
  fmms:
    driver: bridge

services:
  backend:
    restart: always
    build: backend
    ports:
      - 28080:8080
    expose:
      - 8080
    env_file:
      - variables.env
    volumes:
      - maven:/root/.m2
    networks:
      - fmms

  frontend:
    restart: always
    build: frontend
    command: ["--env=staging"]
    depends_on:
      - backend
    ports:
      - 24200:4200
    expose:
      - 4200
    networks:
      - fmms
    environment:
      - APPLICATION_ENV=staging

volumes:
  maven:
    driver: local
