version: '2'

networks:
  fmmscd:
    driver: bridge

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - fmmscd

  jenkins:
    restart: unless-stopped
    build: .
    ports:
      - 28080:8080
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fmmscd
